import type { SeedDataset } from "./types";

/**
 * Planta de GLP: recepción, almacenamiento, envasado y despacho.
 *
 * Configuración **ficticia** construida sobre la especificación funcional de
 * SIMARP. No representa el inventario real de ninguna empresa, y las
 * frecuencias de mantenimiento son de demostración: las de una planta real las
 * fijan los manuales del fabricante, la clasificación de áreas y los
 * procedimientos autorizados.
 *
 * Qué la hace distinta de los otros sets:
 *
 * 1. **La seguridad manda sobre la aritmética.** Un tercio de los activos son
 *    de criticidad crítica y el área 600 completa está marcada como sistema de
 *    seguridad. Esas órdenes reciben prioridad crítica por regla, no por score.
 * 2. **Redundancia real.** Las bombas, compresores y bombas contraincendios
 *    van en pares A/B. Eso cambia la prioridad: un equipo crítico con respaldo
 *    no es lo mismo que uno sin él.
 * 3. **Estacionalidad.** En Chile el consumo de GLP se dispara en invierno. El
 *    envasado trabaja más horas, el desgaste sube y las fallas se concentran
 *    entre junio y agosto.
 * 4. **Subactivos.** Los cuatro cabezales cuelgan del carrusel y los tres
 *    detectores del sistema de detección de gas: son componentes, no equipos
 *    independientes, y así el Pareto no reparte entre cuatro lo que es un solo
 *    problema.
 */
export const glpDataset: SeedDataset = {
  key: "glp",
  label: "Planta de GLP",
  orderPrefix: "OT",
  estacional: true,
  root: {
    tag: "PGLP-MET-01",
    name: "Planta GLP Metropolitana",
    location: "Recepción, almacenamiento, envasado y despacho · Región Metropolitana",
  },

  groups: [
    {
      group: { tag: "100", name: "Recepción de GLP" },
      equipment: [
        {
          tag: "REC-101",
          name: "Posición de recepción 1",
          assetType: "sistema",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Emerson",
          model: "LoadTec R-200",
          downtimeCostPerHour: 1_850_000,
          failuresPerYear: 5,
          repairHours: [2, 9],
          likelyFailures: ["FM-201", "FM-402", "FM-401"],
          hoursPerDay: 5.5,
          initialHours: 14_200,
        },
        {
          tag: "REC-102",
          name: "Posición de recepción 2",
          assetType: "sistema",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Emerson",
          model: "LoadTec R-200",
          downtimeCostPerHour: 1_850_000,
          failuresPerYear: 4,
          repairHours: [2, 9],
          likelyFailures: ["FM-201", "FM-401"],
          hoursPerDay: 4.8,
          initialHours: 12_600,
        },
        {
          tag: "BRA-101",
          name: "Conjunto de transferencia 1",
          assetType: "conjunto",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Kanon",
          model: "MLA 4",
          downtimeCostPerHour: 1_600_000,
          failuresPerYear: 6,
          repairHours: [2, 11],
          likelyFailures: ["FM-104", "FM-202", "FM-106"],
          hoursPerDay: 5.5,
          initialHours: 14_100,
        },
        {
          tag: "BRA-102",
          name: "Conjunto de transferencia 2",
          assetType: "conjunto",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Kanon",
          model: "MLA 4",
          downtimeCostPerHour: 1_600_000,
          failuresPerYear: 5,
          repairHours: [2, 11],
          likelyFailures: ["FM-104", "FM-106"],
          hoursPerDay: 4.8,
          initialHours: 12_500,
        },
        {
          tag: "FIL-101",
          name: "Filtro de línea 1",
          assetType: "otro",
          criticality: "media",
          hasBackup: true,
          manufacturer: "Parker",
          model: "GLP-400",
          downtimeCostPerHour: 420_000,
          failuresPerYear: 7,
          repairHours: [1, 4],
          likelyFailures: ["FM-305", "FM-104"],
        },
        {
          tag: "FIL-102",
          name: "Filtro de línea 2",
          assetType: "otro",
          criticality: "media",
          hasBackup: true,
          manufacturer: "Parker",
          model: "GLP-400",
          downtimeCostPerHour: 420_000,
          failuresPerYear: 6,
          repairHours: [1, 4],
          likelyFailures: ["FM-305"],
        },
        {
          tag: "MED-101",
          name: "Medidor de transferencia",
          assetType: "instrumento",
          criticality: "alta",
          manufacturer: "Micro Motion",
          model: "CMF300",
          // Sin medición certificada no se puede facturar la recepción.
          downtimeCostPerHour: 2_200_000,
          failuresPerYear: 4,
          repairHours: [2, 8],
          likelyFailures: ["FM-403", "FM-401", "FM-405"],
        },
        {
          tag: "VAL-101",
          name: "Válvula automática de aislamiento 1",
          assetType: "valvula",
          criticality: "critica",
          hasBackup: true,
          manufacturer: "Emerson",
          model: "Bettis RTS",
          downtimeCostPerHour: 3_100_000,
          failuresPerYear: 3,
          repairHours: [2, 10],
          likelyFailures: ["FM-104", "FM-404", "FM-306"],
        },
        {
          tag: "VAL-102",
          name: "Válvula automática de aislamiento 2",
          assetType: "valvula",
          criticality: "critica",
          hasBackup: true,
          manufacturer: "Emerson",
          model: "Bettis RTS",
          downtimeCostPerHour: 3_100_000,
          failuresPerYear: 2,
          repairHours: [2, 10],
          likelyFailures: ["FM-104", "FM-404"],
        },
      ],
    },

    {
      group: { tag: "200", name: "Almacenamiento y transferencia" },
      equipment: [
        {
          tag: "TK-201",
          name: "Estanque GLP 1",
          assetType: "recipiente",
          criticality: "critica",
          hasBackup: true,
          manufacturer: "Tecnovac",
          model: "Horizontal 120 m³",
          downtimeCostPerHour: 4_800_000,
          failuresPerYear: 2,
          repairHours: [4, 24],
          likelyFailures: ["FM-104", "FM-306", "FM-403"],
        },
        {
          tag: "TK-202",
          name: "Estanque GLP 2",
          assetType: "recipiente",
          criticality: "critica",
          hasBackup: true,
          manufacturer: "Tecnovac",
          model: "Horizontal 120 m³",
          downtimeCostPerHour: 4_800_000,
          failuresPerYear: 1,
          repairHours: [4, 24],
          likelyFailures: ["FM-104", "FM-306"],
        },
        {
          tag: "TK-203",
          name: "Estanque GLP 3",
          assetType: "recipiente",
          criticality: "critica",
          hasBackup: true,
          manufacturer: "Tecnovac",
          model: "Horizontal 120 m³",
          downtimeCostPerHour: 4_800_000,
          failuresPerYear: 2,
          repairHours: [4, 24],
          likelyFailures: ["FM-104", "FM-403"],
        },
        {
          tag: "P-201A",
          name: "Bomba de transferencia A",
          assetType: "bomba",
          criticality: "critica",
          hasBackup: true,
          manufacturer: "Blackmer",
          model: "LGL 158",
          // Protagonista del análisis de causa raíz. Los tres eventos de
          // vibración están escritos en `scriptedFailures`, así que aquí se
          // baja la cuota aleatoria y se excluye FM-101 de sus modos
          // probables: si el azar añadiera más vibraciones, la serie de tres
          // dejaría de leerse como una progresión y pasaría a ser ruido.
          downtimeCostPerHour: 3_400_000,
          failuresPerYear: 4,
          repairHours: [3, 14],
          likelyFailures: ["FM-104", "FM-106", "FM-103"],
          hoursPerDay: 12.5,
          initialHours: 38_400,
        },
        {
          tag: "P-201B",
          name: "Bomba de transferencia B",
          assetType: "bomba",
          criticality: "critica",
          hasBackup: true,
          manufacturer: "Blackmer",
          model: "LGL 158",
          downtimeCostPerHour: 3_400_000,
          failuresPerYear: 4,
          repairHours: [3, 14],
          likelyFailures: ["FM-104", "FM-102", "FM-105"],
          hoursPerDay: 9.0,
          initialHours: 29_100,
        },
        {
          tag: "M-201A",
          name: "Motor de bomba A",
          assetType: "motor",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "WEG",
          model: "W22 75 kW",
          downtimeCostPerHour: 1_400_000,
          failuresPerYear: 4,
          repairHours: [2, 10],
          likelyFailures: ["FM-108", "FM-102", "FM-110"],
          hoursPerDay: 12.5,
          initialHours: 38_200,
        },
        {
          tag: "M-201B",
          name: "Motor de bomba B",
          assetType: "motor",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "WEG",
          model: "W22 75 kW",
          downtimeCostPerHour: 1_400_000,
          failuresPerYear: 3,
          repairHours: [2, 10],
          likelyFailures: ["FM-108", "FM-110"],
          hoursPerDay: 9.0,
          initialHours: 28_900,
        },
        {
          tag: "PT-201",
          name: "Transmisor de presión principal",
          assetType: "instrumento",
          criticality: "alta",
          manufacturer: "Rosemount",
          model: "3051S",
          downtimeCostPerHour: 1_250_000,
          failuresPerYear: 5,
          repairHours: [1, 5],
          likelyFailures: ["FM-401", "FM-402", "FM-403"],
        },
        {
          tag: "LT-201",
          name: "Transmisor de nivel del estanque 1",
          assetType: "instrumento",
          criticality: "alta",
          manufacturer: "Rosemount",
          model: "5408",
          downtimeCostPerHour: 1_100_000,
          failuresPerYear: 4,
          repairHours: [1, 5],
          likelyFailures: ["FM-401", "FM-403"],
        },
        {
          tag: "LT-202",
          name: "Transmisor de nivel del estanque 2",
          assetType: "instrumento",
          criticality: "alta",
          manufacturer: "Rosemount",
          model: "5408",
          downtimeCostPerHour: 1_100_000,
          failuresPerYear: 3,
          repairHours: [1, 5],
          likelyFailures: ["FM-402", "FM-401"],
        },
        {
          tag: "LT-203",
          name: "Transmisor de nivel del estanque 3",
          assetType: "instrumento",
          criticality: "alta",
          manufacturer: "Rosemount",
          model: "5408",
          downtimeCostPerHour: 1_100_000,
          failuresPerYear: 5,
          repairHours: [1, 5],
          likelyFailures: ["FM-401", "FM-406"],
        },
        {
          tag: "VAP-201",
          name: "Vaporizador 1",
          assetType: "intercambiador",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Algas-SDI",
          model: "Direct Fired 1200",
          downtimeCostPerHour: 1_900_000,
          failuresPerYear: 6,
          repairHours: [3, 12],
          likelyFailures: ["FM-102", "FM-104", "FM-305"],
          hoursPerDay: 10.5,
          initialHours: 31_800,
        },
        {
          tag: "VAP-202",
          name: "Vaporizador 2",
          assetType: "intercambiador",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Algas-SDI",
          model: "Direct Fired 1200",
          downtimeCostPerHour: 1_900_000,
          failuresPerYear: 5,
          repairHours: [3, 12],
          likelyFailures: ["FM-102", "FM-305"],
          hoursPerDay: 8.0,
          initialHours: 25_300,
        },
      ],
    },

    {
      group: { tag: "300", name: "Envasado de cilindros" },
      equipment: [
        {
          tag: "CAR-301",
          name: "Carrusel de llenado 1",
          assetType: "maquina",
          criticality: "critica",
          manufacturer: "Kosan Crisplant",
          model: "KC-24",
          // Sin carrusel no hay envasado: es el corazón productivo de la planta.
          downtimeCostPerHour: 6_200_000,
          failuresPerYear: 12,
          repairHours: [2, 14],
          likelyFailures: ["FM-201", "FM-207", "FM-210", "FM-204"],
          hoursPerDay: 13.0,
          initialHours: 39_600,
        },
        {
          tag: "MR-301",
          name: "Motorreductor del carrusel",
          assetType: "motor",
          criticality: "alta",
          manufacturer: "SEW-Eurodrive",
          model: "K107 22 kW",
          downtimeCostPerHour: 2_400_000,
          failuresPerYear: 6,
          repairHours: [3, 12],
          likelyFailures: ["FM-204", "FM-102", "FM-206"],
          hoursPerDay: 13.0,
          initialHours: 39_400,
        },
        {
          tag: "ENC-301",
          name: "Encoder de posición",
          assetType: "instrumento",
          criticality: "alta",
          manufacturer: "Sick",
          model: "AFS60",
          downtimeCostPerHour: 1_700_000,
          failuresPerYear: 7,
          repairHours: [1, 4],
          likelyFailures: ["FM-205", "FM-402", "FM-405"],
        },
        {
          tag: "PLC-301",
          name: "PLC de la línea de envasado",
          assetType: "controlador",
          criticality: "critica",
          manufacturer: "Siemens",
          model: "S7-1500",
          downtimeCostPerHour: 5_800_000,
          failuresPerYear: 4,
          repairHours: [2, 10],
          likelyFailures: ["FM-405", "FM-407", "FM-404"],
        },
        {
          tag: "HMI-301",
          name: "HMI de la línea de envasado",
          assetType: "controlador",
          criticality: "alta",
          manufacturer: "Siemens",
          model: "Comfort TP1200",
          downtimeCostPerHour: 1_300_000,
          failuresPerYear: 5,
          repairHours: [1, 5],
          likelyFailures: ["FM-406", "FM-405", "FM-404"],
        },
        {
          tag: "BAL-301",
          name: "Control de peso 1",
          assetType: "instrumento",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Mettler Toledo",
          model: "IND570",
          // Una báscula fuera de tolerancia es un problema legal, no solo técnico.
          downtimeCostPerHour: 2_600_000,
          failuresPerYear: 8,
          repairHours: [1, 6],
          likelyFailures: ["FM-403", "FM-401", "FM-407"],
        },
        {
          tag: "BAL-302",
          name: "Control de peso 2",
          assetType: "instrumento",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Mettler Toledo",
          model: "IND570",
          downtimeCostPerHour: 2_600_000,
          failuresPerYear: 9,
          repairHours: [1, 6],
          likelyFailures: ["FM-403", "FM-401"],
        },
        {
          tag: "DET-301",
          name: "Estación de control de hermeticidad",
          assetType: "seguridad",
          criticality: "critica",
          isSafetySystem: true,
          manufacturer: "Kosan Crisplant",
          model: "LeakTest 4",
          // Un cilindro con fuga que sale de la planta es el peor escenario.
          downtimeCostPerHour: 4_100_000,
          failuresPerYear: 5,
          repairHours: [2, 9],
          likelyFailures: ["FM-504", "FM-501", "FM-505"],
        },
        {
          tag: "TR-301",
          name: "Transportador de entrada",
          assetType: "transportador",
          criticality: "alta",
          manufacturer: "Interroll",
          model: "Chain 320",
          downtimeCostPerHour: 1_800_000,
          failuresPerYear: 11,
          repairHours: [1, 7],
          likelyFailures: ["FM-201", "FM-202", "FM-203"],
          hoursPerDay: 13.0,
          initialHours: 39_200,
        },
        {
          tag: "TR-302",
          name: "Transportador de salida",
          assetType: "transportador",
          criticality: "alta",
          manufacturer: "Interroll",
          model: "Chain 320",
          downtimeCostPerHour: 1_800_000,
          failuresPerYear: 9,
          repairHours: [1, 7],
          likelyFailures: ["FM-201", "FM-203", "FM-204"],
          hoursPerDay: 13.0,
          initialHours: 39_000,
        },
        {
          tag: "MR-302",
          name: "Motorreductor del transportador de entrada",
          assetType: "motor",
          criticality: "media",
          manufacturer: "SEW-Eurodrive",
          model: "R77 4 kW",
          downtimeCostPerHour: 760_000,
          failuresPerYear: 6,
          repairHours: [2, 8],
          likelyFailures: ["FM-204", "FM-102", "FM-206"],
          hoursPerDay: 13.0,
          initialHours: 38_800,
        },
        {
          tag: "MR-303",
          name: "Motorreductor del transportador de salida",
          assetType: "motor",
          criticality: "media",
          manufacturer: "SEW-Eurodrive",
          model: "R77 4 kW",
          downtimeCostPerHour: 760_000,
          failuresPerYear: 5,
          repairHours: [2, 8],
          likelyFailures: ["FM-204", "FM-206"],
          hoursPerDay: 13.0,
          initialHours: 38_700,
        },
        {
          tag: "REJ-301",
          name: "Sistema de rechazo de cilindros",
          assetType: "otro",
          criticality: "alta",
          manufacturer: "Festo",
          model: "DSBC-63",
          downtimeCostPerHour: 1_450_000,
          failuresPerYear: 8,
          repairHours: [1, 5],
          likelyFailures: ["FM-208", "FM-306", "FM-205"],
        },
        {
          tag: "CAB-301-01",
          name: "Cabezal de llenado 1",
          assetType: "otro",
          criticality: "alta",
          parentTag: "CAR-301",
          manufacturer: "Kosan Crisplant",
          model: "FH-24",
          downtimeCostPerHour: 980_000,
          failuresPerYear: 7,
          repairHours: [1, 5],
          likelyFailures: ["FM-104", "FM-403"],
        },
        {
          tag: "CAB-301-02",
          name: "Cabezal de llenado 2",
          assetType: "otro",
          criticality: "alta",
          parentTag: "CAR-301",
          manufacturer: "Kosan Crisplant",
          model: "FH-24",
          downtimeCostPerHour: 980_000,
          failuresPerYear: 6,
          repairHours: [1, 5],
          likelyFailures: ["FM-104", "FM-403"],
        },
        {
          tag: "CAB-301-03",
          name: "Cabezal de llenado 3",
          assetType: "otro",
          criticality: "alta",
          parentTag: "CAR-301",
          manufacturer: "Kosan Crisplant",
          model: "FH-24",
          // El del documento: desviación repetida de llenado.
          downtimeCostPerHour: 980_000,
          failuresPerYear: 10,
          repairHours: [1, 5],
          likelyFailures: ["FM-403", "FM-104", "FM-401"],
        },
        {
          tag: "CAB-301-04",
          name: "Cabezal de llenado 4",
          assetType: "otro",
          criticality: "alta",
          parentTag: "CAR-301",
          manufacturer: "Kosan Crisplant",
          model: "FH-24",
          downtimeCostPerHour: 980_000,
          failuresPerYear: 6,
          repairHours: [1, 5],
          likelyFailures: ["FM-104", "FM-401"],
        },
      ],
    },

    {
      group: { tag: "400", name: "Despacho a granel" },
      equipment: [
        {
          tag: "DES-401",
          name: "Posición de carga 1",
          assetType: "sistema",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Emerson",
          model: "LoadTec D-300",
          downtimeCostPerHour: 2_100_000,
          failuresPerYear: 6,
          repairHours: [2, 9],
          likelyFailures: ["FM-104", "FM-401", "FM-306"],
          hoursPerDay: 7.5,
          initialHours: 22_400,
        },
        {
          tag: "DES-402",
          name: "Posición de carga 2",
          assetType: "sistema",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Emerson",
          model: "LoadTec D-300",
          downtimeCostPerHour: 2_100_000,
          failuresPerYear: 5,
          repairHours: [2, 9],
          likelyFailures: ["FM-104", "FM-401"],
          hoursPerDay: 6.5,
          initialHours: 19_700,
        },
        {
          tag: "P-401A",
          name: "Bomba de despacho A",
          assetType: "bomba",
          criticality: "critica",
          hasBackup: true,
          manufacturer: "Corken",
          model: "Z2000",
          downtimeCostPerHour: 3_600_000,
          failuresPerYear: 7,
          repairHours: [3, 13],
          likelyFailures: ["FM-104", "FM-101", "FM-103"],
          hoursPerDay: 7.5,
          initialHours: 22_900,
        },
        {
          tag: "P-401B",
          name: "Bomba de despacho B",
          assetType: "bomba",
          criticality: "critica",
          hasBackup: true,
          manufacturer: "Corken",
          model: "Z2000",
          downtimeCostPerHour: 3_600_000,
          failuresPerYear: 5,
          repairHours: [3, 13],
          likelyFailures: ["FM-104", "FM-103"],
          hoursPerDay: 6.5,
          initialHours: 19_400,
        },
        {
          tag: "MED-401",
          name: "Medidor de despacho 1",
          assetType: "instrumento",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Micro Motion",
          model: "CMF400",
          downtimeCostPerHour: 2_300_000,
          failuresPerYear: 5,
          repairHours: [1, 7],
          likelyFailures: ["FM-403", "FM-401"],
        },
        {
          tag: "MED-402",
          name: "Medidor de despacho 2",
          assetType: "instrumento",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Micro Motion",
          model: "CMF400",
          downtimeCostPerHour: 2_300_000,
          failuresPerYear: 4,
          repairHours: [1, 7],
          likelyFailures: ["FM-403", "FM-405"],
        },
        {
          tag: "VAL-401",
          name: "Válvula automática de despacho 1",
          assetType: "valvula",
          criticality: "critica",
          hasBackup: true,
          manufacturer: "Emerson",
          model: "Bettis RTS",
          downtimeCostPerHour: 3_000_000,
          failuresPerYear: 3,
          repairHours: [2, 10],
          likelyFailures: ["FM-104", "FM-404", "FM-306"],
        },
        {
          tag: "VAL-402",
          name: "Válvula automática de despacho 2",
          assetType: "valvula",
          criticality: "critica",
          hasBackup: true,
          manufacturer: "Emerson",
          model: "Bettis RTS",
          downtimeCostPerHour: 3_000_000,
          failuresPerYear: 2,
          repairHours: [2, 10],
          likelyFailures: ["FM-104", "FM-404"],
        },
      ],
    },

    {
      group: { tag: "500", name: "Servicios auxiliares" },
      equipment: [
        {
          tag: "COMP-501A",
          name: "Compresor de aire A",
          assetType: "compresor",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Atlas Copco",
          model: "GA 37 VSD+",
          // Sin aire de instrumentos las válvulas automáticas no operan.
          downtimeCostPerHour: 1_700_000,
          failuresPerYear: 8,
          repairHours: [2, 9],
          likelyFailures: ["FM-302", "FM-305", "FM-301"],
          hoursPerDay: 14.5,
          initialHours: 44_100,
        },
        {
          tag: "COMP-501B",
          name: "Compresor de aire B",
          assetType: "compresor",
          criticality: "alta",
          hasBackup: true,
          manufacturer: "Atlas Copco",
          model: "GA 37 VSD+",
          downtimeCostPerHour: 1_700_000,
          failuresPerYear: 6,
          repairHours: [2, 9],
          likelyFailures: ["FM-302", "FM-308", "FM-301"],
          hoursPerDay: 9.5,
          initialHours: 29_800,
        },
        {
          tag: "SEC-501",
          name: "Secador de aire",
          assetType: "otro",
          criticality: "media",
          manufacturer: "Atlas Copco",
          model: "FD 150",
          downtimeCostPerHour: 540_000,
          failuresPerYear: 6,
          repairHours: [1, 5],
          likelyFailures: ["FM-306", "FM-305"],
          hoursPerDay: 14.5,
          initialHours: 43_800,
        },
        {
          tag: "REC-501",
          name: "Estanque receptor de aire",
          assetType: "recipiente",
          criticality: "alta",
          manufacturer: "Tecnovac",
          model: "AR-3000",
          downtimeCostPerHour: 880_000,
          failuresPerYear: 2,
          repairHours: [1, 6],
          likelyFailures: ["FM-308", "FM-306"],
        },
        {
          tag: "GEN-501",
          name: "Grupo electrógeno de emergencia",
          assetType: "generador",
          criticality: "critica",
          manufacturer: "Cummins",
          model: "C900 D5",
          // Si corta la red y este no parte, la planta queda a oscuras con
          // producto inflamable dentro.
          downtimeCostPerHour: 4_500_000,
          failuresPerYear: 4,
          repairHours: [2, 12],
          likelyFailures: ["FM-307", "FM-108", "FM-302"],
          // Solo pruebas semanales: su horómetro casi no avanza.
          hoursPerDay: 0.35,
          initialHours: 1_050,
        },
        {
          tag: "UPS-501",
          name: "UPS de automatización",
          assetType: "tablero",
          criticality: "alta",
          manufacturer: "Schneider",
          model: "Galaxy VS 40 kVA",
          downtimeCostPerHour: 1_900_000,
          failuresPerYear: 5,
          repairHours: [1, 8],
          likelyFailures: ["FM-404", "FM-108", "FM-110"],
        },
        {
          tag: "TGBT-501",
          name: "Tablero general de baja tensión",
          assetType: "tablero",
          criticality: "critica",
          manufacturer: "Schneider",
          model: "Prisma P",
          downtimeCostPerHour: 5_400_000,
          failuresPerYear: 2,
          repairHours: [3, 16],
          likelyFailures: ["FM-110", "FM-108", "FM-404"],
        },
        {
          tag: "MCC-501",
          name: "Centro de control de motores",
          assetType: "tablero",
          criticality: "critica",
          manufacturer: "Schneider",
          model: "Okken",
          downtimeCostPerHour: 4_900_000,
          failuresPerYear: 3,
          repairHours: [3, 14],
          likelyFailures: ["FM-108", "FM-110", "FM-109"],
        },
      ],
    },

    {
      group: { tag: "600", name: "Seguridad y emergencias" },
      equipment: [
        {
          tag: "RCI-601",
          name: "Bomba principal RCI",
          assetType: "bomba",
          criticality: "critica",
          isSafetySystem: true,
          hasBackup: true,
          manufacturer: "Patterson",
          model: "HSC 1500 gpm",
          downtimeCostPerHour: 5_200_000,
          failuresPerYear: 3,
          repairHours: [2, 12],
          likelyFailures: ["FM-501", "FM-502", "FM-506"],
          hoursPerDay: 0.25,
          initialHours: 780,
        },
        {
          tag: "RCI-602",
          name: "Bomba de respaldo RCI",
          assetType: "bomba",
          criticality: "critica",
          isSafetySystem: true,
          hasBackup: true,
          manufacturer: "Clarke",
          model: "JU6H Diesel",
          downtimeCostPerHour: 5_200_000,
          failuresPerYear: 4,
          repairHours: [2, 12],
          likelyFailures: ["FM-502", "FM-506", "FM-501"],
          hoursPerDay: 0.2,
          initialHours: 610,
        },
        {
          tag: "RCI-603",
          name: "Bomba jockey",
          assetType: "bomba",
          criticality: "alta",
          isSafetySystem: true,
          manufacturer: "Grundfos",
          model: "CR 15-5",
          downtimeCostPerHour: 1_200_000,
          failuresPerYear: 6,
          repairHours: [1, 6],
          likelyFailures: ["FM-104", "FM-501"],
          hoursPerDay: 2.2,
          initialHours: 6_700,
        },
        {
          tag: "RCI-604",
          name: "Tablero de control RCI",
          assetType: "tablero",
          criticality: "critica",
          isSafetySystem: true,
          manufacturer: "Tornatech",
          model: "GPD",
          downtimeCostPerHour: 4_700_000,
          failuresPerYear: 3,
          repairHours: [1, 8],
          likelyFailures: ["FM-502", "FM-505", "FM-503"],
        },
        {
          tag: "DG-601",
          name: "Sistema detector de gas",
          assetType: "seguridad",
          criticality: "critica",
          isSafetySystem: true,
          manufacturer: "Dräger",
          model: "REGARD 7000",
          downtimeCostPerHour: 6_000_000,
          failuresPerYear: 3,
          repairHours: [1, 8],
          likelyFailures: ["FM-505", "FM-502", "FM-504"],
        },
        {
          tag: "DG-601-01",
          name: "Detector de gas del área de recepción",
          assetType: "seguridad",
          criticality: "critica",
          isSafetySystem: true,
          parentTag: "DG-601",
          manufacturer: "Dräger",
          model: "PIR 7000",
          downtimeCostPerHour: 3_800_000,
          failuresPerYear: 5,
          repairHours: [1, 5],
          likelyFailures: ["FM-504", "FM-501", "FM-506"],
        },
        {
          tag: "DG-601-02",
          name: "Detector de gas del área de estanques",
          assetType: "seguridad",
          criticality: "critica",
          isSafetySystem: true,
          parentTag: "DG-601",
          manufacturer: "Dräger",
          model: "PIR 7000",
          downtimeCostPerHour: 3_800_000,
          failuresPerYear: 6,
          repairHours: [1, 5],
          likelyFailures: ["FM-504", "FM-506", "FM-502"],
        },
        {
          tag: "DG-601-03",
          name: "Detector de gas del área de envasado",
          assetType: "seguridad",
          criticality: "critica",
          isSafetySystem: true,
          parentTag: "DG-601",
          manufacturer: "Dräger",
          model: "PIR 7000",
          downtimeCostPerHour: 3_800_000,
          failuresPerYear: 7,
          repairHours: [1, 5],
          likelyFailures: ["FM-506", "FM-504", "FM-501"],
        },
        {
          tag: "ESD-601",
          name: "Sistema de parada de emergencia",
          assetType: "seguridad",
          criticality: "critica",
          isSafetySystem: true,
          manufacturer: "HIMA",
          model: "HIMax",
          downtimeCostPerHour: 7_500_000,
          failuresPerYear: 2,
          repairHours: [2, 10],
          likelyFailures: ["FM-505", "FM-502", "FM-506"],
        },
        {
          tag: "ALM-601",
          name: "Sistema general de alarmas",
          assetType: "seguridad",
          criticality: "critica",
          isSafetySystem: true,
          manufacturer: "Notifier",
          model: "NFS2-3030",
          downtimeCostPerHour: 3_200_000,
          failuresPerYear: 4,
          repairHours: [1, 6],
          likelyFailures: ["FM-503", "FM-505", "FM-502"],
        },
      ],
    },
  ],

  /**
   * Modos de falla agrupados por familia de equipo, como los define la
   * especificación. La numeración por centenas —100 bombas, 200 transporte,
   * 300 compresores, 400 instrumentación, 500 seguridad— permite leer de un
   * vistazo a qué familia pertenece una falla en el Pareto.
   */
  failureModes: [
    // 1xx · Bombas y motores
    { code: "FM-101", name: "Vibración elevada", category: "mecanica" },
    { code: "FM-102", name: "Temperatura elevada", category: "mecanica" },
    { code: "FM-103", name: "Pérdida de rendimiento", category: "operacional" },
    { code: "FM-104", name: "Falla de sello", category: "mecanica" },
    { code: "FM-105", name: "Ruido anormal", category: "mecanica" },
    { code: "FM-106", name: "Desalineación", category: "mecanica" },
    { code: "FM-107", name: "Rodamiento degradado", category: "mecanica" },
    { code: "FM-108", name: "Falla del motor", category: "electrica" },
    { code: "FM-109", name: "Señal de instrumento incorrecta", category: "instrumentacion" },
    { code: "FM-110", name: "Parada por protección", category: "electrica" },

    // 2xx · Transportadores y carrusel
    { code: "FM-201", name: "Atasco", category: "operacional" },
    { code: "FM-202", name: "Desalineación de transporte", category: "mecanica" },
    { code: "FM-203", name: "Cadena con desgaste", category: "mecanica" },
    { code: "FM-204", name: "Rodamiento degradado en transmisión", category: "mecanica" },
    { code: "FM-205", name: "Sensor sin señal", category: "instrumentacion" },
    { code: "FM-206", name: "Motorreductor detenido", category: "mecanica" },
    { code: "FM-207", name: "Velocidad irregular", category: "operacional" },
    { code: "FM-208", name: "Rechazos repetitivos", category: "operacional" },
    { code: "FM-209", name: "Detención inesperada", category: "operacional" },
    { code: "FM-210", name: "Error de comunicación con PLC", category: "instrumentacion" },

    // 3xx · Compresores y aire
    { code: "FM-301", name: "Presión insuficiente", category: "neumatica" },
    { code: "FM-302", name: "Temperatura elevada de compresor", category: "mecanica" },
    { code: "FM-303", name: "Vibración elevada de compresor", category: "mecanica" },
    { code: "FM-304", name: "Consumo eléctrico anormal", category: "electrica" },
    { code: "FM-305", name: "Filtro saturado", category: "operacional" },
    { code: "FM-306", name: "Presencia anormal de humedad", category: "operacional" },
    { code: "FM-307", name: "Falla de partida", category: "electrica" },
    { code: "FM-308", name: "Fuga de aire", category: "neumatica" },

    // 4xx · Instrumentación y automatización
    { code: "FM-401", name: "Lectura inestable", category: "instrumentacion" },
    { code: "FM-402", name: "Pérdida de señal", category: "instrumentacion" },
    { code: "FM-403", name: "Desviación de medición", category: "instrumentacion" },
    { code: "FM-404", name: "Falla de alimentación", category: "electrica" },
    { code: "FM-405", name: "Error de comunicación", category: "instrumentacion" },
    { code: "FM-406", name: "Pantalla sin respuesta", category: "instrumentacion" },
    { code: "FM-407", name: "Módulo de entrada o salida defectuoso", category: "instrumentacion" },

    // 5xx · Sistemas de seguridad
    { code: "FM-501", name: "Equipo no disponible", category: "operacional" },
    { code: "FM-502", name: "Falla de alimentación de sistema de seguridad", category: "electrica" },
    { code: "FM-503", name: "Alarma no reconocida", category: "instrumentacion" },
    { code: "FM-504", name: "Dispositivo fuera de calibración", category: "instrumentacion" },
    { code: "FM-505", name: "Pérdida de comunicación", category: "instrumentacion" },
    { code: "FM-506", name: "Prueba funcional no satisfactoria", category: "operacional" },
  ],

  technicians: [
    { name: "Claudio Bustamante", email: "jefe.mantenimiento@plantaglp.cl", role: "jefe", specialty: "Jefe de Mantenimiento", hourlyRate: 58_000 },
    { name: "Marcela Herrera", email: "planificador@plantaglp.cl", role: "planificador", specialty: "Planificadora de Mantenimiento", hourlyRate: 46_000 },
    { name: "Gonzalo Tapia", email: "supervisor.turno@plantaglp.cl", role: "planificador", specialty: "Supervisor de Turno", hourlyRate: 44_000 },
    { name: "Rodrigo Paredes", email: "mecanico1@plantaglp.cl", role: "tecnico", specialty: "Mecánico de Planta", hourlyRate: 34_000 },
    { name: "Felipe Cárdenas", email: "mecanico2@plantaglp.cl", role: "tecnico", specialty: "Mecánico de Envasado", hourlyRate: 32_000 },
    { name: "Andrea Soto", email: "electrico@plantaglp.cl", role: "tecnico", specialty: "Eléctrica de Planta", hourlyRate: 36_000 },
    { name: "Jorge Maldonado", email: "instrumentista@plantaglp.cl", role: "tecnico", specialty: "Instrumentista", hourlyRate: 38_000 },
    { name: "Paula Riquelme", email: "prevencion@plantaglp.cl", role: "tecnico", specialty: "Prevención de Riesgos", hourlyRate: 40_000 },
    { name: "Sebastián Muñoz", email: "mantenedor@plantaglp.cl", role: "tecnico", specialty: "Mantenedor Polivalente", hourlyRate: 30_000 },
  ],

  /**
   * La recurrencia de la bomba de transferencia A, escrita a mano.
   *
   * Tres eventos sobre el mismo equipo con severidad creciente y el mismo modo
   * de falla. Es el caso que la especificación pide para demostrar el análisis
   * de causa raíz, y por eso no se deja al azar: si el generador no los
   * produjera, la demostración quedaría sin su momento más importante.
   *
   * La progresión es la que se ve en una planta real cuando se trata el
   * síntoma y no la causa: se cambia el rodamiento, vuelve a los tres meses
   * con temperatura además de vibración, y al tercero el equipo se detiene
   * solo. Nueve horas de parada la primera vez, veintiséis la última.
   */
  scriptedFailures: [
    {
      assetTag: "P-201A",
      monthsAgo: 8,
      failureCode: "FM-101",
      title: "Vibración elevada en Bomba de transferencia A",
      description:
        "La guardia reporta vibración por sobre lo habitual en la bomba de transferencia A durante el trasvase nocturno. Se deriva a mantenimiento mecánico.",
      downtimeMinutes: 540,
      repairHours: 6.5,
      partsCost: 1_240_000,
      resolution:
        "Rodamiento lado acople reemplazado. Se verificó vibración dentro de rango al reponer el servicio.",
    },
    {
      assetTag: "P-201A",
      monthsAgo: 5,
      failureCode: "FM-101",
      title: "Vibración elevada con aumento de temperatura en Bomba de transferencia A",
      description:
        "Reaparece la vibración en la bomba de transferencia A, esta vez acompañada de temperatura elevada en el descanso lado acople. Se opera con la bomba B mientras se interviene.",
      downtimeMinutes: 960,
      repairHours: 11,
      partsCost: 2_180_000,
      resolution:
        "Segundo reemplazo de rodamiento en el año. Se registró temperatura de descanso previa a la intervención.",
    },
    {
      assetTag: "P-201A",
      monthsAgo: 2,
      failureCode: "FM-101",
      title: "Detención de Bomba de transferencia A por vibración",
      description:
        "La bomba de transferencia A se detiene por protección durante la operación de recepción. Tercer evento de vibración del año sobre el mismo equipo.",
      downtimeMinutes: 1_560,
      repairHours: 18,
      partsCost: 3_650_000,
      resolution:
        "Reemplazo de rodamientos y verificación de acople. Queda pendiente definir la causa de fondo: la frecuencia entre eventos se acorta.",
    },
  ],

  /**
   * Los doce planes de la especificación. Las frecuencias son de
   * demostración: las reales las fijan los manuales del fabricante y los
   * procedimientos autorizados de la planta.
   */
  pmTemplates: [
    { name: "Inspección operacional", trigger: "calendario", frequencyDays: 7, frequencyHours: null, estimatedHours: "1.50" },
    { name: "Inspección mecánica", trigger: "calendario", frequencyDays: 30, frequencyHours: null, estimatedHours: "3.00" },
    { name: "Control eléctrico", trigger: "calendario", frequencyDays: 90, frequencyHours: null, estimatedHours: "4.00" },
    { name: "Servicio de compresor", trigger: "ambos", frequencyDays: 90, frequencyHours: 500, estimatedHours: "4.00" },
    { name: "Servicio de motorreductor", trigger: "ambos", frequencyDays: 180, frequencyHours: 1_000, estimatedHours: "5.00" },
    { name: "Verificación de báscula", trigger: "calendario", frequencyDays: 30, frequencyHours: null, estimatedHours: "2.00" },
    { name: "Verificación de detectores de gas", trigger: "calendario", frequencyDays: 90, frequencyHours: null, estimatedHours: "3.00" },
    { name: "Prueba funcional RCI", trigger: "calendario", frequencyDays: 30, frequencyHours: null, estimatedHours: "4.00" },
    { name: "Respaldo de automatización", trigger: "calendario", frequencyDays: 90, frequencyHours: null, estimatedHours: "2.00" },
    { name: "Revisión de UPS", trigger: "calendario", frequencyDays: 90, frequencyHours: null, estimatedHours: "2.50" },
    { name: "Servicio de generador", trigger: "ambos", frequencyDays: 180, frequencyHours: 250, estimatedHours: "6.00" },
    { name: "Inspección mayor de activos críticos", trigger: "calendario", frequencyDays: 365, frequencyHours: null, estimatedHours: "16.00" },
  ],
};
