import type { SeedDataset } from "./types";

/**
 * Segundo buque de la flota: un granelero, deliberadamente distinto del
 * portacontenedores.
 *
 * No es una copia con otros nombres. Un granelero no lleva planta reefer —su
 * carga no se refrigera— pero sí grúas de cubierta propias para operar en
 * puertos sin infraestructura, y bombas de achique de bodega que el
 * portacontenedores no necesita. Motor Wärtsilä en vez de MAN, y un tramo de
 * horómetros más bajo por ser un casco más nuevo.
 *
 * Esa diferencia es a propósito: si los dos buques tuvieran los mismos activos,
 * un fallo de aislamiento entre organizaciones pasaría desapercibido.
 */
export const marineDataset2: SeedDataset = {
  key: "marino-granelero",
  label: "Buque granelero",
  orderPrefix: "OT",
  root: {
    tag: "MN-MAGAL",
    name: "M/N Estrecho de Magallanes",
    location: "Granelero · 58.000 DWT",
  },

  groups: [
    {
      group: { tag: "SM-100", name: "Sala de Máquinas — Propulsión" },
      equipment: [
        {
          tag: "MP-101",
          name: "Motor principal Wärtsilä 6RT-flex50",
          criticality: "A",
          manufacturer: "Wärtsilä",
          model: "6RT-flex50-D",
          downtimeCostPerHour: 3_600_000,
          failuresPerYear: 6,
          repairHours: [6, 28],
          likelyFailures: ["FM-001", "FM-002", "FM-004"],
          hoursPerDay: 15.5,
          initialHours: 31_000,
        },
        {
          tag: "MP-102",
          name: "Turbocompresor Mitsubishi MET53",
          criticality: "A",
          manufacturer: "Mitsubishi",
          model: "MET53MB",
          downtimeCostPerHour: 2_700_000,
          failuresPerYear: 4,
          repairHours: [5, 18],
          likelyFailures: ["FM-003", "FM-001"],
          hoursPerDay: 15.5,
          initialHours: 29_800,
        },
        {
          tag: "MP-103",
          name: "Reductor y eje propulsor",
          criticality: "A",
          manufacturer: "Wärtsilä",
          model: "SCV 90",
          downtimeCostPerHour: 3_900_000,
          failuresPerYear: 2,
          repairHours: [12, 44],
          likelyFailures: ["FM-005", "FM-012", "FM-006"],
          hoursPerDay: 15.5,
          initialHours: 30_400,
        },
        {
          tag: "MP-104",
          name: "Enfriador central de agua dulce",
          criticality: "B",
          manufacturer: "Alfa Laval",
          model: "T20-BFG",
          downtimeCostPerHour: 880_000,
          failuresPerYear: 5,
          repairHours: [3, 11],
          likelyFailures: ["FM-013", "FM-012"],
          hoursPerDay: 16.0,
          initialHours: 33_100,
        },
      ],
    },

    {
      group: { tag: "SM-200", name: "Sala de Máquinas — Generación y Servicios" },
      equipment: [
        {
          tag: "GA-201",
          name: "Motor auxiliar N.º 1 Daihatsu 6DK-20",
          criticality: "B",
          manufacturer: "Daihatsu Diesel",
          model: "6DK-20",
          downtimeCostPerHour: 690_000,
          failuresPerYear: 7,
          repairHours: [4, 15],
          likelyFailures: ["FM-001", "FM-004", "FM-014"],
          hoursPerDay: 9.5,
          initialHours: 19_400,
        },
        {
          tag: "GA-202",
          name: "Motor auxiliar N.º 2 Daihatsu 6DK-20",
          criticality: "B",
          manufacturer: "Daihatsu Diesel",
          model: "6DK-20",
          downtimeCostPerHour: 690_000,
          failuresPerYear: 8,
          repairHours: [4, 15],
          likelyFailures: ["FM-001", "FM-010", "FM-014"],
          hoursPerDay: 8.5,
          initialHours: 17_900,
        },
        {
          tag: "GA-203",
          name: "Generador de emergencia Volvo Penta D13",
          criticality: "A",
          manufacturer: "Volvo Penta",
          model: "D13 MG",
          downtimeCostPerHour: 1_700_000,
          failuresPerYear: 2,
          repairHours: [4, 12],
          likelyFailures: ["FM-014", "FM-009"],
          hoursPerDay: 0.25,
          initialHours: 890,
        },
        {
          tag: "GA-204",
          name: "Purificadora de aceite lubricante",
          criticality: "A",
          manufacturer: "Mitsubishi Kakoki",
          model: "SJ-20T",
          downtimeCostPerHour: 2_100_000,
          failuresPerYear: 9,
          repairHours: [2, 8],
          likelyFailures: ["FM-011", "FM-005", "FM-015"],
          hoursPerDay: 19.0,
          initialHours: 35_600,
        },
        {
          tag: "GA-205",
          name: "Caldera auxiliar de fuel",
          criticality: "B",
          manufacturer: "Alfa Laval Aalborg",
          model: "OL-4",
          downtimeCostPerHour: 580_000,
          failuresPerYear: 4,
          repairHours: [5, 18],
          likelyFailures: ["FM-007", "FM-013", "FM-012"],
          hoursPerDay: 12.0,
          initialHours: 26_700,
        },
        {
          tag: "GA-206",
          name: "Compresor de aire de trabajo",
          criticality: "B",
          manufacturer: "Tanabe",
          model: "H-64",
          downtimeCostPerHour: 740_000,
          failuresPerYear: 5,
          repairHours: [2, 9],
          likelyFailures: ["FM-016", "FM-005"],
          hoursPerDay: 5.0,
          initialHours: 11_200,
        },
      ],
    },

    {
      group: { tag: "CB-300", name: "Cubierta y Manejo de Carga" },
      equipment: [
        {
          tag: "CG-301",
          name: "Grúa de bodega N.º 1 (30 t)",
          criticality: "A",
          manufacturer: "MacGregor",
          model: "GLB 30/26",
          // En un granelero las grúas son el negocio: sin ellas no hay descarga.
          downtimeCostPerHour: 2_900_000,
          failuresPerYear: 9,
          repairHours: [3, 16],
          likelyFailures: ["FM-010", "FM-005", "FM-012"],
          hoursPerDay: 4.5,
          initialHours: 9_800,
        },
        {
          tag: "CG-302",
          name: "Grúa de bodega N.º 2 (30 t)",
          criticality: "A",
          manufacturer: "MacGregor",
          model: "GLB 30/26",
          downtimeCostPerHour: 2_900_000,
          failuresPerYear: 7,
          repairHours: [3, 16],
          likelyFailures: ["FM-010", "FM-012"],
          hoursPerDay: 4.0,
          initialHours: 9_100,
        },
        {
          tag: "CG-303",
          name: "Bomba de achique de bodegas",
          criticality: "B",
          manufacturer: "Shinko",
          model: "SVA-150",
          downtimeCostPerHour: 780_000,
          failuresPerYear: 6,
          repairHours: [2, 9],
          likelyFailures: ["FM-005", "FM-012", "FM-011"],
          hoursPerDay: 2.0,
          initialHours: 4_600,
        },
        {
          tag: "CG-304",
          name: "Tapas de escotilla hidráulicas",
          criticality: "B",
          manufacturer: "MacGregor",
          model: "Folding 5",
          downtimeCostPerHour: 1_150_000,
          failuresPerYear: 6,
          repairHours: [2, 10],
          likelyFailures: ["FM-010", "FM-012"],
          hoursPerDay: 0.5,
          initialHours: 1_950,
        },
        {
          tag: "CG-305",
          name: "Servomotor (steering gear)",
          criticality: "A",
          manufacturer: "Kawasaki",
          model: "K-Steer 45",
          downtimeCostPerHour: 3_400_000,
          failuresPerYear: 3,
          repairHours: [5, 17],
          likelyFailures: ["FM-010", "FM-008"],
          hoursPerDay: 15.5,
          initialHours: 30_900,
        },
        {
          tag: "CG-306",
          name: "Molinete y maquinillas de amarre",
          criticality: "C",
          manufacturer: "Kawasaki",
          model: "MW-22",
          downtimeCostPerHour: 420_000,
          failuresPerYear: 4,
          repairHours: [2, 8],
          likelyFailures: ["FM-010", "FM-012"],
          hoursPerDay: 0.7,
          initialHours: 2_800,
        },
      ],
    },
  ],

  failureModes: [
    { code: "FM-001", name: "Desgaste de camisa, aros o cojinetes", category: "mecanica" },
    { code: "FM-002", name: "Fuga o mala pulverización de inyector", category: "mecanica" },
    { code: "FM-003", name: "Avería de turbocompresor", category: "mecanica" },
    { code: "FM-004", name: "Temperatura alta de gases de escape", category: "operacional" },
    { code: "FM-005", name: "Fuga en sello mecánico o retén", category: "mecanica" },
    { code: "FM-006", name: "Desalineamiento de acople", category: "mecanica" },
    { code: "FM-007", name: "Fuga de vapor en serpentín", category: "mecanica" },
    { code: "FM-008", name: "Falla de variador o arrancador", category: "electrica" },
    { code: "FM-009", name: "Sensor o transmisor sin señal", category: "instrumentacion" },
    { code: "FM-010", name: "Fuga en circuito hidráulico", category: "hidraulica" },
    { code: "FM-011", name: "Obstrucción por lodos o contaminación de combustible", category: "operacional" },
    { code: "FM-012", name: "Corrosión por agua salada", category: "estructural" },
    { code: "FM-013", name: "Incrustación y ensuciamiento de intercambiador", category: "operacional" },
    { code: "FM-014", name: "Entrada de agua salada en aceite lubricante", category: "operacional" },
    { code: "FM-015", name: "Emulsión de agua en combustible", category: "operacional" },
    { code: "FM-016", name: "Fuga en línea de aire comprimido", category: "neumatica" },
  ],

  technicians: [
    { name: "Óscar Bahamonde", email: "jefe.maquinas@estrechomagallanes.cl", role: "jefe", specialty: "Jefe de Máquinas", hourlyRate: 60_000 },
    { name: "Javiera Núñez", email: "primer.oficial@estrechomagallanes.cl", role: "planificador", specialty: "Primer Ingeniero", hourlyRate: 47_000 },
    { name: "Cristián Ampuero", email: "segundo.maquinas@estrechomagallanes.cl", role: "tecnico", specialty: "Segundo Ingeniero", hourlyRate: 37_000 },
    { name: "Nicolás Barría", email: "tercer.maquinas@estrechomagallanes.cl", role: "tecnico", specialty: "Tercer Ingeniero", hourlyRate: 31_000 },
    { name: "Fernanda Ojeda", email: "electricista@estrechomagallanes.cl", role: "tecnico", specialty: "Oficial Electricista", hourlyRate: 35_000 },
    { name: "Luis Millalonco", email: "mecanico@estrechomagallanes.cl", role: "tecnico", specialty: "Mecánico", hourlyRate: 27_000 },
    { name: "Camila Uribe", email: "engrasador@estrechomagallanes.cl", role: "tecnico", specialty: "Engrasador", hourlyRate: 21_000 },
  ],

  pmTemplates: [
    { name: "Rutina de 500 h — inspección y ajuste", trigger: "horas", frequencyDays: null, frequencyHours: 500, estimatedHours: "4.00" },
    { name: "Cambio de aceite y filtros", trigger: "ambos", frequencyDays: 180, frequencyHours: 2_000, estimatedHours: "5.00" },
    { name: "Prueba de carga de grúas y certificación", trigger: "calendario", frequencyDays: 365, frequencyHours: null, estimatedHours: "8.00" },
    { name: "Inspección de sacrificio anódico y corrosión", trigger: "calendario", frequencyDays: 180, frequencyHours: null, estimatedHours: "6.00" },
    { name: "Overhaul de culatas y camisas", trigger: "horas", frequencyDays: null, frequencyHours: 12_000, estimatedHours: "36.00" },
  ],
};
