import type { SeedDataset } from "./types";

/**
 * Faena minera de cobre a rajo abierto, con planta concentradora.
 *
 * Es el caso más distinto a un buque, y por eso vale como demostración: aquí el
 * activo que manda no es un motor sino la **línea de proceso**. Un molino SAG
 * detenido para la planta entera, y por eso su costo de indisponibilidad es un
 * orden de magnitud mayor que el de cualquier equipo marino de esta base.
 *
 * La flota móvil (camiones, palas) lleva horómetro y se mantiene por horas de
 * marcha; la planta se mantiene por calendario, atada a las detenciones
 * programadas. Esa mezcla es la realidad del rubro y ejercita los dos
 * disparadores del plan preventivo.
 */
export const mineraDataset: SeedDataset = {
  key: "minera",
  label: "Faena minera de cobre",
  orderPrefix: "OT",
  root: {
    tag: "FAENA-ANDINA",
    name: "Minera Cerro Bayo",
    location: "Rajo abierto y concentradora · Región de Antofagasta",
  },

  groups: [
    {
      group: { tag: "CH-100", name: "Chancado" },
      equipment: [
        {
          tag: "CH-101",
          name: "Chancador primario giratorio 60x89",
          criticality: "A",
          manufacturer: "Metso",
          model: "Superior MK-III 60-89",
          // Sin chancado primario no entra mineral a la planta: se detiene todo.
          downtimeCostPerHour: 18_500_000,
          failuresPerYear: 5,
          repairHours: [6, 30],
          likelyFailures: ["FM-001", "FM-004", "FM-009"],
          hoursPerDay: 20.5,
          initialHours: 61_400,
        },
        {
          tag: "CH-102",
          name: "Chancador secundario de cono",
          criticality: "A",
          manufacturer: "Metso",
          model: "HP900",
          downtimeCostPerHour: 7_200_000,
          failuresPerYear: 7,
          repairHours: [4, 18],
          likelyFailures: ["FM-001", "FM-002", "FM-006"],
          hoursPerDay: 19.0,
          initialHours: 54_900,
        },
        {
          tag: "CH-103",
          name: "Correa transportadora CV-01 (overland)",
          criticality: "A",
          manufacturer: "ContiTech",
          model: "St-2500 · 3.400 m",
          downtimeCostPerHour: 9_800_000,
          failuresPerYear: 11,
          repairHours: [2, 14],
          likelyFailures: ["FM-003", "FM-005", "FM-001"],
          hoursPerDay: 20.0,
          initialHours: 58_200,
        },
        {
          tag: "CH-104",
          name: "Harnero vibratorio banana 8x24",
          criticality: "B",
          manufacturer: "Haver & Boecker",
          model: "Niagara XL-Class",
          downtimeCostPerHour: 2_400_000,
          failuresPerYear: 9,
          repairHours: [2, 10],
          likelyFailures: ["FM-006", "FM-001", "FM-011"],
          hoursPerDay: 19.5,
          initialHours: 52_100,
        },
        {
          tag: "CH-105",
          name: "Colector de polvo de chancado",
          criticality: "C",
          manufacturer: "Donaldson",
          model: "Torit PowerCore",
          downtimeCostPerHour: 380_000,
          failuresPerYear: 6,
          repairHours: [1, 6],
          likelyFailures: ["FM-012", "FM-010"],
          hoursPerDay: 19.0,
          initialHours: 47_800,
        },
      ],
    },

    {
      group: { tag: "ML-200", name: "Molienda y Clasificación" },
      equipment: [
        {
          tag: "ML-201",
          name: "Molino SAG 36' x 20'",
          criticality: "A",
          manufacturer: "FLSmidth",
          model: "SAG 36x20 · 16 MW",
          // El activo más caro de la faena: su parada arrastra a la planta entera.
          downtimeCostPerHour: 24_000_000,
          failuresPerYear: 4,
          repairHours: [10, 48],
          likelyFailures: ["FM-007", "FM-001", "FM-008"],
          hoursPerDay: 21.0,
          initialHours: 64_700,
        },
        {
          tag: "ML-202",
          name: "Molino de bolas 22' x 36'",
          criticality: "A",
          manufacturer: "FLSmidth",
          model: "BM 22x36 · 8 MW",
          downtimeCostPerHour: 15_600_000,
          failuresPerYear: 5,
          repairHours: [8, 36],
          likelyFailures: ["FM-007", "FM-001", "FM-006"],
          hoursPerDay: 21.0,
          initialHours: 63_900,
        },
        {
          tag: "ML-203",
          name: "Batería de hidrociclones D-26",
          criticality: "B",
          manufacturer: "Weir Minerals",
          model: "Cavex 650CVX",
          downtimeCostPerHour: 3_900_000,
          failuresPerYear: 12,
          repairHours: [1, 7],
          likelyFailures: ["FM-011", "FM-002"],
          hoursPerDay: 21.0,
          initialHours: 62_300,
        },
        {
          tag: "ML-204",
          name: "Bomba de pulpa GEHO de alimentación",
          criticality: "A",
          manufacturer: "Weir Minerals",
          model: "Warman 550 MCR",
          downtimeCostPerHour: 6_400_000,
          failuresPerYear: 14,
          repairHours: [2, 12],
          likelyFailures: ["FM-002", "FM-011", "FM-005"],
          hoursPerDay: 20.5,
          initialHours: 59_600,
        },
        {
          tag: "ML-205",
          name: "Accionamiento de anillo (ring motor) SAG",
          criticality: "A",
          manufacturer: "ABB",
          model: "GMD 16 MW",
          downtimeCostPerHour: 21_000_000,
          failuresPerYear: 2,
          repairHours: [12, 60],
          likelyFailures: ["FM-008", "FM-013", "FM-009"],
          hoursPerDay: 21.0,
          initialHours: 64_100,
        },
      ],
    },

    {
      group: { tag: "FL-300", name: "Flotación y Espesamiento" },
      equipment: [
        {
          tag: "FL-301",
          name: "Celdas de flotación rougher 300 m³",
          criticality: "A",
          manufacturer: "Outotec",
          model: "TankCell e300",
          downtimeCostPerHour: 8_700_000,
          failuresPerYear: 8,
          repairHours: [3, 16],
          likelyFailures: ["FM-006", "FM-010", "FM-008"],
          hoursPerDay: 21.0,
          initialHours: 61_800,
        },
        {
          tag: "FL-302",
          name: "Espesador de concentrado 45 m",
          criticality: "B",
          manufacturer: "FLSmidth",
          model: "E-Duc 45",
          downtimeCostPerHour: 4_100_000,
          failuresPerYear: 5,
          repairHours: [4, 20],
          likelyFailures: ["FM-006", "FM-013"],
          hoursPerDay: 21.0,
          initialHours: 60_400,
        },
        {
          tag: "FL-303",
          name: "Filtro de prensa de concentrado",
          criticality: "B",
          manufacturer: "Metso",
          model: "VPA 1530",
          downtimeCostPerHour: 3_300_000,
          failuresPerYear: 9,
          repairHours: [2, 11],
          likelyFailures: ["FM-010", "FM-012", "FM-005"],
          hoursPerDay: 18.0,
          initialHours: 48_900,
        },
        {
          tag: "FL-304",
          name: "Planta de reactivos y dosificación",
          criticality: "C",
          manufacturer: "ProMinent",
          model: "Sigma X",
          downtimeCostPerHour: 620_000,
          failuresPerYear: 7,
          repairHours: [1, 5],
          likelyFailures: ["FM-009", "FM-002", "FM-012"],
          hoursPerDay: 21.0,
          initialHours: 58_700,
        },
      ],
    },

    {
      group: { tag: "MI-400", name: "Flota Mina" },
      equipment: [
        {
          tag: "CX-401",
          name: "Camión de extracción CAEX 793F N.º 1",
          criticality: "A",
          manufacturer: "Caterpillar",
          model: "793F · 227 t",
          downtimeCostPerHour: 2_800_000,
          failuresPerYear: 13,
          repairHours: [3, 18],
          likelyFailures: ["FM-010", "FM-014", "FM-001"],
          hoursPerDay: 19.5,
          initialHours: 41_300,
        },
        {
          tag: "CX-402",
          name: "Camión de extracción CAEX 793F N.º 2",
          criticality: "A",
          manufacturer: "Caterpillar",
          model: "793F · 227 t",
          downtimeCostPerHour: 2_800_000,
          failuresPerYear: 15,
          repairHours: [3, 18],
          likelyFailures: ["FM-010", "FM-014", "FM-004"],
          hoursPerDay: 19.0,
          initialHours: 44_800,
        },
        {
          tag: "PA-403",
          name: "Pala hidráulica de cargío",
          criticality: "A",
          manufacturer: "Komatsu",
          model: "PC8000-6 · 42 m³",
          downtimeCostPerHour: 11_200_000,
          failuresPerYear: 10,
          repairHours: [4, 26],
          likelyFailures: ["FM-010", "FM-008", "FM-001"],
          hoursPerDay: 18.5,
          initialHours: 37_600,
        },
        {
          tag: "PF-404",
          name: "Perforadora de tiros de voladura",
          criticality: "B",
          manufacturer: "Epiroc",
          model: "Pit Viper 351",
          downtimeCostPerHour: 3_600_000,
          failuresPerYear: 11,
          repairHours: [2, 14],
          likelyFailures: ["FM-010", "FM-012", "FM-001"],
          hoursPerDay: 16.0,
          initialHours: 29_400,
        },
        {
          tag: "MO-405",
          name: "Motoniveladora de caminos",
          criticality: "C",
          manufacturer: "Caterpillar",
          model: "16M3",
          downtimeCostPerHour: 540_000,
          failuresPerYear: 8,
          repairHours: [2, 9],
          likelyFailures: ["FM-010", "FM-014"],
          hoursPerDay: 12.0,
          initialHours: 21_800,
        },
        {
          tag: "CA-406",
          name: "Camión aljibe de supresión de polvo",
          criticality: "C",
          manufacturer: "Caterpillar",
          model: "777G WT",
          downtimeCostPerHour: 460_000,
          failuresPerYear: 7,
          repairHours: [1, 8],
          likelyFailures: ["FM-002", "FM-010"],
          hoursPerDay: 14.0,
          initialHours: 25_100,
        },
      ],
    },

    {
      group: { tag: "SE-500", name: "Servicios y Suministro Eléctrico" },
      equipment: [
        {
          tag: "SE-501",
          name: "Subestación principal 220/23 kV",
          criticality: "A",
          manufacturer: "Siemens",
          model: "8DA10",
          downtimeCostPerHour: 22_000_000,
          failuresPerYear: 2,
          repairHours: [4, 24],
          likelyFailures: ["FM-013", "FM-008", "FM-009"],
        },
        {
          tag: "SE-502",
          name: "Compresores de aire de planta",
          criticality: "B",
          manufacturer: "Atlas Copco",
          model: "GA 315 VSD",
          downtimeCostPerHour: 1_900_000,
          failuresPerYear: 8,
          repairHours: [2, 9],
          likelyFailures: ["FM-012", "FM-005"],
          hoursPerDay: 20.0,
          initialHours: 56_300,
        },
        {
          tag: "SE-503",
          name: "Estación de bombeo de agua de proceso",
          criticality: "B",
          manufacturer: "KSB",
          model: "Omega 300-670",
          downtimeCostPerHour: 3_100_000,
          failuresPerYear: 9,
          repairHours: [2, 11],
          likelyFailures: ["FM-002", "FM-005", "FM-008"],
          hoursPerDay: 21.0,
          initialHours: 60_900,
        },
        {
          tag: "SE-504",
          name: "Grupo electrógeno de respaldo",
          criticality: "B",
          manufacturer: "Cummins",
          model: "C2250 D5",
          downtimeCostPerHour: 890_000,
          failuresPerYear: 4,
          repairHours: [2, 10],
          likelyFailures: ["FM-004", "FM-008"],
          // Solo pruebas semanales: su horómetro casi no avanza.
          hoursPerDay: 0.4,
          initialHours: 1_180,
        },
      ],
    },
  ],

  failureModes: [
    { code: "FM-001", name: "Desgaste de revestimiento o elemento de desgaste", category: "mecanica" },
    { code: "FM-002", name: "Desgaste de impulsor o carcasa por abrasión de pulpa", category: "mecanica" },
    { code: "FM-003", name: "Desalineamiento o desviación de correa", category: "mecanica" },
    { code: "FM-004", name: "Sobrecalentamiento por exigencia de proceso", category: "operacional" },
    { code: "FM-005", name: "Fuga en sello mecánico o retén", category: "mecanica" },
    { code: "FM-006", name: "Falla de rodamiento o descanso principal", category: "mecanica" },
    { code: "FM-007", name: "Desgaste o desprendimiento de lifter de molino", category: "mecanica" },
    { code: "FM-008", name: "Falla de motor, variador o partida", category: "electrica" },
    { code: "FM-009", name: "Sensor o transmisor sin señal", category: "instrumentacion" },
    { code: "FM-010", name: "Fuga en circuito hidráulico", category: "hidraulica" },
    { code: "FM-011", name: "Obstrucción o embanque de línea de pulpa", category: "operacional" },
    { code: "FM-012", name: "Fuga en línea de aire comprimido", category: "neumatica" },
    { code: "FM-013", name: "Falla de aislación eléctrica", category: "electrica" },
    { code: "FM-014", name: "Fisura estructural en chasis o tolva", category: "estructural" },
    { code: "FM-015", name: "Corrosión por ambiente ácido de proceso", category: "estructural" },
  ],

  technicians: [
    { name: "Rodrigo Zúñiga", email: "jefe.mantenimiento@cerrobayo.cl", role: "jefe", specialty: "Jefe de Mantenimiento", hourlyRate: 62_000 },
    { name: "Paulina Carvajal", email: "planificador@cerrobayo.cl", role: "planificador", specialty: "Planificadora de Mantenimiento", hourlyRate: 48_000 },
    { name: "Héctor Tapia", email: "supervisor.planta@cerrobayo.cl", role: "planificador", specialty: "Supervisor de Planta", hourlyRate: 45_000 },
    { name: "Marcelo Pizarro", email: "mecanico1@cerrobayo.cl", role: "tecnico", specialty: "Mecánico de Molienda", hourlyRate: 34_000 },
    { name: "Ignacio Rojas", email: "electrico@cerrobayo.cl", role: "tecnico", specialty: "Eléctrico de Planta", hourlyRate: 36_000 },
    { name: "Daniela Contreras", email: "instrumentista@cerrobayo.cl", role: "tecnico", specialty: "Instrumentista", hourlyRate: 38_000 },
    { name: "Víctor Araya", email: "mantenedor.mina@cerrobayo.cl", role: "tecnico", specialty: "Mantenedor Flota Mina", hourlyRate: 33_000 },
    { name: "Karen Espinoza", email: "lubricadora@cerrobayo.cl", role: "tecnico", specialty: "Lubricación y Predictivo", hourlyRate: 29_000 },
  ],

  pmTemplates: [
    { name: "Ronda de lubricación y engrase", trigger: "calendario", frequencyDays: 15, frequencyHours: null, estimatedHours: "3.00" },
    { name: "Análisis de vibraciones y termografía", trigger: "calendario", frequencyDays: 30, frequencyHours: null, estimatedHours: "4.00" },
    { name: "Mantención preventiva de flota — 250 h", trigger: "horas", frequencyDays: null, frequencyHours: 250, estimatedHours: "6.00" },
    { name: "Cambio de aceite y filtros de flota", trigger: "ambos", frequencyDays: 90, frequencyHours: 500, estimatedHours: "5.00" },
    { name: "Inspección de revestimientos de molino", trigger: "horas", frequencyDays: null, frequencyHours: 2_000, estimatedHours: "12.00" },
    { name: "Detención programada de planta", trigger: "calendario", frequencyDays: 180, frequencyHours: null, estimatedHours: "48.00" },
  ],
};
