import type { SeedDataset } from "./types";

/**
 * Remolcador de puerto ASD (Azimuth Stern Drive).
 *
 * El contraste con los buques de carga es lo interesante: un remolcador es
 * pequeño —una veintena de activos— pero trabaja a tirones. No navega catorce
 * horas seguidas; hace maniobras cortas de asistencia a máxima potencia, con
 * arranques y paradas constantes. Eso castiga embragues, propulsores y
 * acoplamientos mucho más que la marcha continua de un portacontenedores, y se
 * refleja en más fallas al año sobre menos horas de horómetro.
 *
 * Además lleva equipos que ningún carguero tiene: el gancho y la maquinilla de
 * remolque, que son literalmente su herramienta de trabajo, y el sistema
 * contraincendios FiFi con el que asiste emergencias en puerto.
 */
export const remolcadorDataset: SeedDataset = {
  key: "remolcador",
  label: "Remolcador de puerto",
  orderPrefix: "OT",
  root: {
    tag: "RAM-HUALPEN",
    name: "R/M Hualpén",
    location: "Remolcador ASD · 65 t de bollard pull · Puerto de San Vicente",
  },

  groups: [
    {
      group: { tag: "PR-100", name: "Propulsión" },
      equipment: [
        {
          tag: "MP-101",
          name: "Motor principal Caterpillar 3516C babor",
          criticality: "A",
          manufacturer: "Caterpillar",
          model: "3516C · 2.000 kW",
          // Con un motor fuera, el remolcador pierde la mitad de su tiro:
          // no puede asistir a un buque y la maniobra se cancela.
          downtimeCostPerHour: 2_100_000,
          failuresPerYear: 8,
          repairHours: [4, 20],
          likelyFailures: ["FM-001", "FM-002", "FM-004"],
          hoursPerDay: 6.5,
          initialHours: 18_400,
        },
        {
          tag: "MP-102",
          name: "Motor principal Caterpillar 3516C estribor",
          criticality: "A",
          manufacturer: "Caterpillar",
          model: "3516C · 2.000 kW",
          downtimeCostPerHour: 2_100_000,
          failuresPerYear: 9,
          repairHours: [4, 20],
          likelyFailures: ["FM-001", "FM-004", "FM-003"],
          hoursPerDay: 6.5,
          initialHours: 18_900,
        },
        {
          tag: "PR-103",
          name: "Propulsor azimutal babor (Z-drive)",
          criticality: "A",
          manufacturer: "Schottel",
          model: "SRP 490",
          // Las maniobras a tope de potencia con giros constantes castigan el
          // azimutal mucho más que la marcha recta de un buque de carga.
          downtimeCostPerHour: 2_600_000,
          failuresPerYear: 7,
          repairHours: [6, 30],
          likelyFailures: ["FM-006", "FM-005", "FM-010"],
          hoursPerDay: 6.5,
          initialHours: 18_200,
        },
        {
          tag: "PR-104",
          name: "Propulsor azimutal estribor (Z-drive)",
          criticality: "A",
          manufacturer: "Schottel",
          model: "SRP 490",
          downtimeCostPerHour: 2_600_000,
          failuresPerYear: 6,
          repairHours: [6, 30],
          likelyFailures: ["FM-006", "FM-010", "FM-012"],
          hoursPerDay: 6.5,
          initialHours: 18_100,
        },
        {
          tag: "PR-105",
          name: "Embragues y acoplamientos elásticos",
          criticality: "A",
          manufacturer: "Vulkan",
          model: "Rato-S 3005",
          failuresPerYear: 6,
          repairHours: [3, 14],
          downtimeCostPerHour: 1_800_000,
          likelyFailures: ["FM-007", "FM-006"],
          hoursPerDay: 6.5,
          initialHours: 18_300,
        },
      ],
    },

    {
      group: { tag: "AU-200", name: "Auxiliares de Máquinas" },
      equipment: [
        {
          tag: "AU-201",
          name: "Generador auxiliar N.º 1",
          criticality: "B",
          manufacturer: "Caterpillar",
          model: "C4.4 · 99 kW",
          downtimeCostPerHour: 460_000,
          failuresPerYear: 7,
          repairHours: [2, 10],
          likelyFailures: ["FM-004", "FM-008", "FM-001"],
          hoursPerDay: 11.0,
          initialHours: 29_600,
        },
        {
          tag: "AU-202",
          name: "Generador auxiliar N.º 2",
          criticality: "B",
          manufacturer: "Caterpillar",
          model: "C4.4 · 99 kW",
          downtimeCostPerHour: 460_000,
          failuresPerYear: 6,
          repairHours: [2, 10],
          likelyFailures: ["FM-004", "FM-008"],
          hoursPerDay: 9.5,
          initialHours: 25_800,
        },
        {
          tag: "AU-203",
          name: "Central hidráulica de cubierta",
          criticality: "A",
          manufacturer: "Parker",
          model: "PV270",
          downtimeCostPerHour: 1_400_000,
          failuresPerYear: 9,
          repairHours: [2, 12],
          likelyFailures: ["FM-010", "FM-005", "FM-009"],
          hoursPerDay: 5.0,
          initialHours: 13_700,
        },
        {
          tag: "AU-204",
          name: "Enfriador de quilla y circuito de agua dulce",
          criticality: "B",
          manufacturer: "Bloksma",
          model: "KC-320",
          downtimeCostPerHour: 620_000,
          failuresPerYear: 5,
          repairHours: [2, 11],
          likelyFailures: ["FM-011", "FM-012"],
          hoursPerDay: 6.5,
          initialHours: 18_500,
        },
        {
          tag: "AU-205",
          name: "Compresor de aire de arranque",
          criticality: "B",
          manufacturer: "Sperre",
          model: "HL2/77",
          downtimeCostPerHour: 380_000,
          failuresPerYear: 6,
          repairHours: [1, 7],
          likelyFailures: ["FM-013", "FM-005"],
          hoursPerDay: 1.6,
          initialHours: 4_400,
        },
        {
          tag: "AU-206",
          name: "Separadora de combustible",
          criticality: "C",
          manufacturer: "Alfa Laval",
          model: "P 605",
          downtimeCostPerHour: 240_000,
          failuresPerYear: 5,
          repairHours: [1, 6],
          likelyFailures: ["FM-014", "FM-005"],
          hoursPerDay: 4.0,
          initialHours: 11_200,
        },
      ],
    },

    {
      group: { tag: "RM-300", name: "Equipo de Remolque y Cubierta" },
      equipment: [
        {
          tag: "RM-301",
          name: "Maquinilla de remolque de proa",
          criticality: "A",
          manufacturer: "DMT",
          model: "TW-200 · tiro 200 kN",
          // Es la herramienta de trabajo: sin ella el remolcador no remolca.
          downtimeCostPerHour: 2_400_000,
          failuresPerYear: 10,
          repairHours: [2, 14],
          likelyFailures: ["FM-010", "FM-006", "FM-012"],
          hoursPerDay: 4.5,
          initialHours: 12_600,
        },
        {
          tag: "RM-302",
          name: "Gancho de remolque de escape rápido",
          criticality: "A",
          manufacturer: "Mampaey",
          model: "SWL 90 t",
          downtimeCostPerHour: 2_200_000,
          failuresPerYear: 4,
          repairHours: [1, 8],
          likelyFailures: ["FM-015", "FM-012"],
        },
        {
          tag: "RM-303",
          name: "Maquinilla de popa y molinete",
          criticality: "B",
          manufacturer: "DMT",
          model: "AW-90",
          downtimeCostPerHour: 720_000,
          failuresPerYear: 7,
          repairHours: [2, 9],
          likelyFailures: ["FM-010", "FM-012"],
          hoursPerDay: 2.2,
          initialHours: 6_100,
        },
        {
          tag: "RM-304",
          name: "Defensas de proa y costado",
          criticality: "B",
          manufacturer: "Trelleborg",
          model: "Cylindrical W-Block",
          // Se golpean contra el casco del buque asistido en cada maniobra.
          downtimeCostPerHour: 540_000,
          failuresPerYear: 8,
          repairHours: [2, 10],
          likelyFailures: ["FM-015", "FM-012"],
        },
      ],
    },

    {
      group: { tag: "SE-400", name: "Seguridad y Sistemas del Buque" },
      equipment: [
        {
          tag: "SE-401",
          name: "Sistema contraincendios FiFi-1 (monitores)",
          criticality: "A",
          manufacturer: "FFS",
          model: "FiFi-1 · 2.400 m³/h",
          // Certificado y auditado: si no responde, el remolcador pierde la
          // habilitación para asistir emergencias en puerto.
          downtimeCostPerHour: 1_900_000,
          failuresPerYear: 4,
          repairHours: [2, 12],
          likelyFailures: ["FM-005", "FM-009", "FM-012"],
          hoursPerDay: 0.5,
          initialHours: 1_420,
        },
        {
          tag: "SE-402",
          name: "Bombas contraincendios y de achique",
          criticality: "A",
          manufacturer: "Desmi",
          model: "NSL 150-315",
          downtimeCostPerHour: 1_100_000,
          failuresPerYear: 6,
          repairHours: [1, 8],
          likelyFailures: ["FM-005", "FM-012", "FM-008"],
          hoursPerDay: 1.2,
          initialHours: 3_300,
        },
        {
          tag: "SE-403",
          name: "Servomotor y control de gobierno",
          criticality: "A",
          manufacturer: "Schottel",
          model: "MasterStick",
          downtimeCostPerHour: 2_300_000,
          failuresPerYear: 5,
          repairHours: [2, 12],
          likelyFailures: ["FM-009", "FM-008", "FM-010"],
          hoursPerDay: 6.5,
          initialHours: 18_200,
        },
        {
          tag: "SE-404",
          name: "Equipo de navegación y radiocomunicaciones",
          criticality: "B",
          manufacturer: "Furuno",
          model: "FAR-2228 / FM-8900S",
          downtimeCostPerHour: 480_000,
          failuresPerYear: 6,
          repairHours: [1, 6],
          likelyFailures: ["FM-009", "FM-008"],
          hoursPerDay: 9.0,
          initialHours: 24_100,
        },
        {
          tag: "SE-405",
          name: "Baterías y tableros de 24 V",
          criticality: "B",
          manufacturer: "Victron",
          model: "Quattro 48/10000",
          downtimeCostPerHour: 390_000,
          failuresPerYear: 5,
          repairHours: [1, 6],
          likelyFailures: ["FM-008", "FM-012"],
        },
      ],
    },
  ],

  failureModes: [
    { code: "FM-001", name: "Desgaste de camisa, aros o cojinetes", category: "mecanica" },
    { code: "FM-002", name: "Fuga o mala pulverización de inyector", category: "mecanica" },
    { code: "FM-003", name: "Avería de turbocompresor", category: "mecanica" },
    { code: "FM-004", name: "Temperatura alta por maniobra a plena carga", category: "operacional" },
    { code: "FM-005", name: "Fuga en sello mecánico o retén", category: "mecanica" },
    { code: "FM-006", name: "Falla de engranaje o rodamiento de azimutal", category: "mecanica" },
    { code: "FM-007", name: "Desgaste de embrague o acoplamiento elástico", category: "mecanica" },
    { code: "FM-008", name: "Falla eléctrica de mando o arranque", category: "electrica" },
    { code: "FM-009", name: "Sensor o transmisor sin señal", category: "instrumentacion" },
    { code: "FM-010", name: "Fuga en circuito hidráulico", category: "hidraulica" },
    { code: "FM-011", name: "Incrustación y ensuciamiento de intercambiador", category: "operacional" },
    { code: "FM-012", name: "Corrosión por agua salada", category: "estructural" },
    { code: "FM-013", name: "Fuga en línea de aire comprimido", category: "neumatica" },
    { code: "FM-014", name: "Emulsión de agua en combustible", category: "operacional" },
    { code: "FM-015", name: "Daño estructural por impacto de maniobra", category: "estructural" },
  ],

  technicians: [
    { name: "Sergio Villablanca", email: "jefe.maquinas@remolcadoreshualpen.cl", role: "jefe", specialty: "Jefe de Máquinas", hourlyRate: 55_000 },
    { name: "Andrea Sepúlveda", email: "patron@remolcadoreshualpen.cl", role: "planificador", specialty: "Patrón de Remolcador", hourlyRate: 49_000 },
    { name: "Mauricio Riquelme", email: "motorista@remolcadoreshualpen.cl", role: "tecnico", specialty: "Motorista", hourlyRate: 34_000 },
    { name: "Claudio Vergara", email: "electricista@remolcadoreshualpen.cl", role: "tecnico", specialty: "Electricista Naval", hourlyRate: 35_000 },
    { name: "Patricia Muñoz", email: "marinero@remolcadoreshualpen.cl", role: "tecnico", specialty: "Marinero de Cubierta", hourlyRate: 24_000 },
  ],

  pmTemplates: [
    { name: "Rutina de 250 h — motores principales", trigger: "horas", frequencyDays: null, frequencyHours: 250, estimatedHours: "3.00" },
    { name: "Cambio de aceite y filtros", trigger: "ambos", frequencyDays: 120, frequencyHours: 1_000, estimatedHours: "4.00" },
    { name: "Inspección de propulsores azimutales", trigger: "horas", frequencyDays: null, frequencyHours: 2_000, estimatedHours: "10.00" },
    { name: "Prueba de tiro (bollard pull) y certificación", trigger: "calendario", frequencyDays: 365, frequencyHours: null, estimatedHours: "8.00" },
    { name: "Prueba de sistema FiFi y contraincendios", trigger: "calendario", frequencyDays: 90, frequencyHours: null, estimatedHours: "4.00" },
    { name: "Inspección de cable y gancho de remolque", trigger: "calendario", frequencyDays: 60, frequencyHours: null, estimatedHours: "3.00" },
  ],
};
